titanic:
  name: "Titanic Survival"
  description: "Passenger data with survival labels"
  file: "titanic_sample.csv"
  target: "Survived"
  task: "classification"
adult_income:
  name: "Adult Income"
  description: "US census income classification"
  file: "adult_income_sample.csv"
  target: "income"
  task: "classification"
synthetic_marketing_leads:
  name: "Marketing Leads"
  description: "Synthetic marketing engagement conversion labels"
  file: "synthetic_marketing_leads.csv"
  target: "converted"
  task: "classification"
synthetic_customer_churn:
  name: "Customer Churn"
  description: "Synthetic churn indicators for subscription services"
  file: "synthetic_customer_churn.csv"
  target: "churned"
  task: "classification"
synthetic_credit_scoring:
  name: "Credit Scoring"
  description: "Synthetic credit default classification"
  file: "synthetic_credit_scoring.csv"
  target: "defaulted"
  task: "classification"
synthetic_employee_attrition:
  name: "Employee Attrition"
  description: "Synthetic employee attrition dataset"
  file: "synthetic_employee_attrition.csv"
  target: "left_company"
  task: "classification"
synthetic_loan_approval:
  name: "Loan Approval"
  description: "Synthetic loan application approvals"
  file: "synthetic_loan_approval.csv"
  target: "approved"
  task: "classification"
synthetic_supply_chain:
  name: "Supply Chain Delays"
  description: "Synthetic delivery delay classification"
  file: "synthetic_supply_chain.csv"
  target: "late_delivery"
  task: "classification"
synthetic_patient_readmission:
  name: "Patient Readmission"
  description: "Synthetic hospital readmission labels"
  file: "synthetic_patient_readmission.csv"
  target: "readmitted"
  task: "classification"
synthetic_maintenance:
  name: "Predictive Maintenance"
  description: "Synthetic equipment failure classification"
  file: "synthetic_maintenance.csv"
  target: "failure_within_30d"
  task: "classification"
synthetic_network_intrusion:
  name: "Network Intrusion"
  description: "Synthetic intrusion detection signatures"
  file: "synthetic_network_intrusion.csv"
  target: "intrusion"
  task: "classification"
synthetic_transport_delay:
  name: "Transport Delay"
  description: "Synthetic shipment delay classification"
  file: "synthetic_transport_delay.csv"
  target: "delayed"
  task: "classification"
synthetic_water_quality:
  name: "Water Quality"
  description: "Synthetic potable water indicator"
  file: "synthetic_water_quality.csv"
  target: "is_safe"
  task: "classification"
synthetic_financial_risk:
  name: "Financial Risk"
  description: "Synthetic portfolio risk flags"
  file: "synthetic_financial_risk.csv"
  target: "high_risk"
  task: "classification"
synthetic_energy_consumption:
  name: "Energy Consumption"
  description: "Synthetic energy consumption regression"
  file: "synthetic_energy_consumption.csv"
  target: "consumption_mwh"
  task: "regression"
synthetic_solar_power:
  name: "Solar Power"
  description: "Synthetic solar power plant output"
  file: "synthetic_solar_power.csv"
  target: "power_output_kw"
  task: "regression"
synthetic_healthcare_costs:
  name: "Healthcare Costs"
  description: "Synthetic annual healthcare cost regression"
  file: "synthetic_healthcare_costs.csv"
  target: "annual_cost_k"
  task: "regression"
synthetic_sales_forecast:
  name: "Sales Forecast"
  description: "Synthetic quarterly revenue regression"
  file: "synthetic_sales_forecast.csv"
  target: "quarterly_revenue_k"
  task: "regression"
synthetic_agriculture_yield:
  name: "Agriculture Yield"
  description: "Synthetic crop yield regression"
  file: "synthetic_agriculture_yield.csv"
  target: "yield_tonnes"
  task: "regression"
synthetic_call_center:
  name: "Call Center Satisfaction"
  description: "Synthetic customer satisfaction regression"
  file: "synthetic_call_center.csv"
  target: "satisfaction_score"
  task: "regression"
synthetic_traffic_volume:
  name: "Traffic Volume"
  description: "Synthetic hourly vehicle counts"
  file: "synthetic_traffic_volume.csv"
  target: "vehicles_per_hour"
  task: "regression"
synthetic_customer_lifetime:
  name: "Customer Lifetime Value"
  description: "Synthetic lifetime value regression"
  file: "synthetic_customer_lifetime.csv"
  target: "lifetime_value_k"
  task: "regression"
